DOC-249 init
amplitude/amplitude-docs pull request #347
Opened 2024-10-24 19:48 UTC by markzegarelli

2024-10-30 21:55 UTC, SpencerFleury requested changes

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +The Shopify Plugin plugin installs a version of the [Browser SDK](/docs/sdks/analytics/browser/browser-sdk-2), and adds the script before the `</head>` tag on each of your site's pages.
```suggestion
The Shopify plugin installs a version of the [Browser SDK](/docs/sdks/analytics/browser/browser-sdk-2), and adds the script before the `</head>` tag on each of your site's pages.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +1. Log in to your Shopify account, and find the plugin in the [Shopify App Store](https://apps.shopify.com/amplitude). Click *Install*.
```suggestion
1. Log in to your Shopify account and find the plugin in the [Shopify App Store](https://apps.shopify.com/amplitude). Click *Install*.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +2. Confirm the required plugin permissions, and click *Install*.
```suggestion
2. Confirm the required plugin permissions and click *Install*.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +3. Locate your project's API key, and add it to the Amplitude Settings page in Shopify. Click *Connect*.
```suggestion
3. Locate your project's API key and add it to the Amplitude Settings page in Shopify. Click *Connect*.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +    Disable any enabled ad blocking software in your browser to ensure the plugin setup step can communicate with Amplitude.
```suggestion
    If any ad blocking software is running in your browser, disable it to ensure the plugin setup step can communicate with Amplitude.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +4. A "Connection successful" message indicates the plugin is enabled and connected with Amplitude.
```suggestion
A "Connection successful" message indicates the plugin is enabled and connected with Amplitude.
```

2024-10-30 21:55 UTC, SpencerFleury commented on content/collections/data/en/amplitude-shopify-plugin.md
> +4. A "Connection successful" message indicates the plugin is enabled and connected with Amplitude.
This isn't a step—the user doesn't do anything here—so it doesn't get a number.

2024-11-18 20:42 UTC, katiegeer commented on content/collections/data/en/amplitude-shopify-plugin.md
> +
### About Shopify
[Shopify](https://www.shopify.com/) is an all-in-one commerce platform that allows businesses of any size to create, customize, and manage online stores with ease. It offers tools for product listings, payments, shipping, and customer engagement, streamlining the selling process online, across social media, and in person. With built-in marketing features, analytics, and integrations with third-party apps, Shopify helps business owners track performance and drive sales.

2024-11-18 20:42 UTC, katiegeer commented on content/collections/data/en/amplitude-shopify-plugin.md
> +The Shopify Plugin plugin installs a version of the [Browser SDK](/docs/sdks/analytics/browser/browser-sdk-2), and adds the script before the `</head>` tag on each of your site's pages.
Amplitude also sends all [Default Events](https://amplitude.com/docs/sdks/analytics/browser/migrate-from-marketing-analytics-to-browser-sdk-2-0#default-event-tracking).

2024-11-18 20:43 UTC, katiegeer commented on content/collections/data/en/amplitude-shopify-plugin.md
> +
### Considerations

- **Performance**: The packages we utilize on the frontend is roughly 167kb. To give a rough idea of the performance impact I generated 6 different Lighthouse Performance reports. 3 with the Amplitude packages, and 3 without. Without the Amplitude packages, the average performance score was 98. With the packages, the average Performance score was 96.
- **Session replay may not display as expected**. Shopify’s UI heavily relies on animations, specifically the fade-in animation. The animation responsible for changing the opacity of the UI from 0 to 1 is not consistently picked up by session replay, which is why elements appear to be missing.

2024-11-19 00:01 UTC, zacbennett commented on content/collections/data/en/amplitude-shopify-plugin.md
> +* Performance: The packages Amplitude provides are roughly 167kb total size. In testing, Shopify stores with Amplitude installed registered an average lighthouse score of 96, compared to an average s
```suggestion
* Performance: The packages Amplitude provides are roughly 167kb total size, but will vary depending on which products you utilize. In testing, Shopify stores with Amplitude installed registered an average lighthouse score of 96, compared to an average score of 98 without Amplitude.
```

2024-11-19 00:09 UTC, zacbennett commented on content/collections/data/en/amplitude-shopify-plugin.md
> +* Session replay may not display as expected. Shopify’s UI relies on animations, specifically the fade-in animation. Session Replay doesn't capture the animation consistently, which may cause element
I think this is okay to take out. This ended up being an issue with my test store, and we haven't received reports from customers that they are running into this

2024-11-19 00:12 UTC, zacbennett commented on content/collections/data/en/amplitude-shopify-plugin.md
> +3. Locate your project's API key and add it to the Amplitude Settings page in Shopify. Click *Connect*.
We also just added a step where a user needs to indicate where they want to store their data. 
![image](https://github.com/user-attachments/assets/55dd6837-bcbc-4ae5-a767-8ded81dbca12)

2024-11-19 00:13 UTC, zacbennett commented
There's a lot more info we can add here, specifically with regards to what events we sent and their properties. Take a look at this FAQ doc https://amplitude.atlassian.net/wiki/spaces/GROWTH/pages/2578874543/Shopify+App+FAQ

2024-12-02 23:55 UTC, markzegarelli commented
> There's a lot more info we can add here, specifically with regards to what events we sent and their properties. Take a look at this FAQ doc https://amplitude.atlassian.net/wiki/spaces/GROWTH/pages/2578874543/Shopify+App+FAQ

Thanks @zacbennett! I updated the [article](https://amplitude-docs-git-doc-249-amplitude-inc.vercel.app/docs/data/amplitude-shopify-plugin) with the properties and events listed in the FAQ.

As far as Session Replay and Web Experiment, I'll mainly link out to those sections, but is there anything you think would be good to capture in this article? For example, I'll mention that for Session Replay, it needs a non-zero sample rate.

2024-12-03 21:32 UTC, zacbennett commented
> > There's a lot more info we can add here, specifically with regards to what events we sent and their properties. Take a look at this FAQ doc https://amplitude.atlassian.net/wiki/spaces/GROWTH/pages/2578874543/Shopify+App+FAQ
> 
> Thanks @zacbennett! I updated the [article](https://amplitude-docs-git-doc-249-amplitude-inc.vercel.app/docs/data/amplitude-shopify-plugin) with the properties and events listed in the FAQ.
> 
> As far as Session Replay and Web Experiment, I'll mainly link out to those sections, but is there anything you think would be good to capture in this article? For example, I'll mention that for Session Replay, it needs a non-zero sample rate.

Awesome. With regards to the Web Experiment, there is a minor flicker when implementing web experiment. There is a manual work around this is mentioned [here](https://amplitude-docs-i2yd1y5ep-amplitude-inc.vercel.app/docs/web-experiment/implementation#shopify). Think it might be helpful to link here.

2024-12-03 21:37 UTC, zacbennett commented
Two common questions that I've gotten which I think are worth including here are:
1. What is the difference between Order Created and Checkout Created?
2. As well as, how is user id determined?

Both of these are answered in the FAQ doc, and I think would be worthwhile to add here. Otherwise everything LGTM!

2024-12-03 22:32 UTC, zacbennett approved these changes

2024-12-03 22:39 UTC, merged