AMP-112976 [streaming] Updated streaming transformations doc for GA
amplitude/amplitude-docs pull request #368
Opened 2024-11-04 19:46 UTC by kg-datamonster

Event Streaming Transformations is now GA. Updating the doc to reflect the same.

2024-11-05 18:14 UTC, SpencerFleury requested changes

2024-11-05 18:14 UTC, SpencerFleury commented on content/collections/data/en/streaming-transformations.md
> +* Like saved charts, if there is a change in the name of Custom Event or Derived Property, existing syncs that use these will not work as expected because you need to update the sync configs to use t
```suggestion
* When changing the names of custom events or derived properties, don't forget to update any existing sync configs that use them. Syncs require up-to-date event and property names in order to work properly. Note that this only applies to the name of the transformation: changing the underlying definition of a custom event or derived property doesn't affect syncing.
```

2024-11-05 18:14 UTC, SpencerFleury commented on content/collections/data/en/streaming-transformations.md
> +* You can't stream **channel classifiers** directly. However, this is available on request. Channels, which act like derived properties applied in real-time when querying within Amplitude, are mainly
```suggestion
* You can only stream **channel classifiers** directly by requesting it from Amplitude. Channels, which act like derived properties applied in real-time when querying within Amplitude, are mainly used by marketers to define their acquisition channels based on UTM and referrer data. Although they're used as a property where values map to specific rules on existing properties, these channel properties can't be selected when setting up the sync in either event filters, or when sending more properties to the destination, unless you've explicitly enabled this feature.
```

2024-11-05 18:14 UTC, SpencerFleury commented on content/collections/data/en/streaming-transformations.md
> +Support for channel classifiers to be selected in the event streaming sync config is available on request. Email integrations@Amplitude.com with your Organization ID and App IDs if you're interested
```suggestion
Support for selecting channel classifiers in the event streaming sync config is available on request. Email integrations@Amplitude.com with your organization ID and app IDs for access.
```

2024-11-05 18:24 UTC, kg-datamonster commented
Thanks for the review and suggestions @SpencerFleury 🙌

2024-11-06 00:50 UTC, SpencerFleury approved these changes

2024-11-06 00:50 UTC, merged