feat: add browser SDK migration guide from JS to TS 2.x
amplitude/amplitude-docs pull request #369
Opened 2024-11-05 00:24 UTC by Mercy811

JIRA: [AMP-118022]

Currently, we only have migration guides
- from JS SDK to Browser TS 1.x
- from Browser TS 1.x to Browser TS 2.x
This PR adds the one from JS SDK to Browser TS 2.x.

2024-11-05 18:01 UTC, SpencerFleury requested changes

2024-11-05 18:01 UTC, SpencerFleury commented on content/collections/browser_sdk/en/migrate-from-javascript-sdk-to-browser-sdk-2-0.md
> +For `amplitude-js`, one `init` callback function for executing any function after initialization and two separate callback functions are passed for success and error network request. With `@amplitude
```suggestion
`amplitude-js` passes one `init` callback function for executing any function after initialization and two separate callback functions for success and error network requests. With `@amplitude/analytics-browser@2+` supporting promises (and async/await), the asynchronous methods like `init()`, `track()`, `identify()`, `groupIdentify()` return a custom promise interface.
```

2024-11-05 23:37 UTC, Mercy811 commented on content/collections/browser_sdk/en/migrate-from-javascript-sdk-to-browser-sdk-2-0.md
> +* improved maketing attribution tracking
Thanks @SpencerFleury, I capitalize all items at https://github.com/amplitude/amplitude-docs/pull/369/commits/42f71b731fd30a06e2948b912f4dea6b8dafe5d1

2024-11-05 23:40 UTC, Mercy811 commented on content/collections/browser_sdk/en/migrate-from-javascript-sdk-to-browser-sdk-2-0.md
> +The `clearUserProperties` API has been removed, use the unified `identify` API to remove user properties.
Is there a local linter I can install and fix it myself in the future?

2024-11-06 00:49 UTC, SpencerFleury approved these changes

2024-11-06 17:49 UTC, merged