AMP-120844 [ga4-import] draft created
amplitude/amplitude-docs pull request #448
Opened 2024-12-23 23:40 UTC by bh202205

2025-01-24 07:45 UTC, fzqgriffin commented on content/collections/source-catalog/en/ga4.md
> +## Add GA4 as a source
@bh202205 can we have a section before this to explain how ga4 source in general? That's what customer had escalated to us a lot, so clarifying that in public doc can help both customer and us a lot. 

Example: https://segment.com/docs/connections/sources/catalog/cloud-apps/facebook-ads/#sync

2025-01-24 18:21 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +## Add GA4 as a source
1. Load amount / how much load
2. which load

2025-01-24 19:43 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +## Add GA4 as a source
Section added. Let me know if this makes sense to you.

2025-01-24 19:52 UTC, fzqgriffin reviewed
LGTM overall. left 2 comments.

2025-01-24 19:52 UTC, fzqgriffin commented on content/collections/source-catalog/en/ga4.md
> +    Once your data is synced to the specified GCS bucket, it will be imported into Amplitude. Please note that it may take some time for your data to be fully available in Amplitude. We appreciate yo
let's rephrase it by removing the call out in waiting since that could raise some concerns. Something like

```
Once data is ready in GCS bucket, we will import data into Amplitude on your behalf.
```

2025-01-24 19:52 UTC, fzqgriffin commented on content/collections/source-catalog/en/ga4.md
> +    * Catch-up Importing:
would be helpful to also describe how initial batch works, and how next batch imports to ensure all data will be imported.

2025-01-24 19:59 UTC, markzegarelli requested changes

2025-01-24 19:59 UTC, markzegarelli commented on content/collections/source-catalog/en/ga4.md
> +With Amplitude's Google Analytics 4 integration, you can ingest Google Analutics 4 data into your Amplitude project.
```suggestion
With Amplitude's Google Analytics 4 integration, you can ingest Google Analytics 4 data into your Amplitude project.
```

2025-01-24 19:59 UTC, markzegarelli commented on content/collections/source-catalog/en/ga4.md
> +    To handle BigQuery’s export limitations (e.g., export size restrictions), we unload your data from BigQuery to the GCS bucket you provided. This ensures data readiness for ingestion into Amplitud
```suggestion
    To handle BigQuery’s export limitations (for example, export size restrictions), we unload your data from BigQuery to the GCS bucket you provided. This ensures data readiness for ingestion into Amplitude.
```

2025-01-24 19:59 UTC, markzegarelli commented on content/collections/source-catalog/en/ga4.md
> +    Once your data is synced to the specified GCS bucket, it will be imported into Amplitude. Please note that it may take some time for your data to be fully available in Amplitude. We appreciate yo
```suggestion
    Once your data syncs to the specified GCS bucket, Amplitude imports it. It may take some time for your data to be fully available in Amplitude. 
```
Can we provide a ballpark "up to" amount of time?

2025-01-24 23:07 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +    Once your data is synced to the specified GCS bucket, it will be imported into Amplitude. Please note that it may take some time for your data to be fully available in Amplitude. We appreciate yo
Rephrased this part.

2025-01-24 23:09 UTC, bh202205 commented
@markzegarelli addressed your comments. Would you mind taking another look?

2025-01-25 00:11 UTC, markzegarelli commented on content/collections/source-catalog/en/ga4.md
> +          * 2025-01-21 to 2025-01-23 in the thrid batch on 2025-01-26.
```suggestion
          * 2025-01-21 to 2025-01-23 in the third batch on 2025-01-26.
```

2025-01-25 00:26 UTC, markzegarelli commented on content/collections/source-catalog/en/ga4.md
> +
@bh202205 I just pushed a bunch of edits. All I think we need  is a sentence or two here that talks about what the BigQuery SQL helper is. Is it an actual thing? Or just the tips that we provide below?

Generally, best practice is to include at least one sentence under each heading, and not have another heading on the next line.

2025-01-25 00:28 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +
This is just some tips we want to provide for our customers because we often hear from them the BigQuery SQL syntax requirement is quite confusing.

2025-01-25 00:32 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +
Description added

2025-01-25 00:33 UTC, bh202205 commented on content/collections/source-catalog/en/ga4.md
> +
Let me know if you have any other questions.

2025-01-25 00:35 UTC, markzegarelli approved these changes

2025-01-25 00:36 UTC, bh202205 commented
@markzegarelli thank you for reviewing the doc for me. I will merge it once the checks finished.

2025-01-25 00:46 UTC, merged